### index
GET {{host}}/
Accept: application/json

### favicon
GET {{host}}/favicon.ico

###
GET {{host}}/404
Accept: application/json

### index
POST {{host}}/
Content-Type: application/json
Accept: application/json

{
  "id": "aa",
  "name": "bb"
}
